# Generated by Django 4.0.4 on 2022-05-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sys_Purchase', '0001_initial'),
        ('sys_RegLog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('order_date', models.DateField()),
                ('begin_date', models.DateField()),
                ('return_date', models.DateField()),
                ('returned', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sys_Purchase.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sys_RegLog.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
