# Generated by Django 4.0.4 on 2022-05-09 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sys_RegLog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Car/')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=15)),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fuel_type', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='Car/')),
                ('rate', models.FloatField(blank=True, null=True)),
                ('rent_price', models.FloatField()),
                ('valid', models.IntegerField()),
                ('returned', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sys_RegLog.owner')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
